apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fsl-frontend-ingress
  namespace: production
spec:
  ingressClassName: nginx
  rules:
    - host: fsl-challenge.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fsl-frontend
                port:
                  number: 8080